name: sons_para_dormir
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: null
  google_fonts: null
  just_audio: null
  just_audio_background: null
  line_icons: ^2.0.3
  riverpod_annotation: null

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
